name: ServiceNow Integration Workflow

on:
  pull_request:
    branches:
      - main  # main 브랜치로 PR 생성 시 실행

jobs:
  service-now-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Change Request in ServiceNow
      run: |
        curl -X POST "https://dev189448.service-now.com/api/now/table/change_request" \
        --user "devops.admin:Servicenow!@3788" \
        --header "Content-Type:application/json" \
        --data '{
          "short_description": "Change request for PR #${{ github.event.pull_request.number }}",
          "priority": "2",
          "description": "Triggered by GitHub Actions"
        }'

    - name: Update Change Request Status
      run: |
        curl -X PATCH "https://dev189448.service-now.com/api/now/table/change_request/<CHANGE_REQUEST_ID>" \
        --user "devops.admin:Servicenow!@3788" \
        --header "Content-Type:application/json" \
        --data '{"state":"3","close_notes":"PR successfully merged"}'
